In [1]:
! pip install pyspark[sql]

Collecting pyspark[sql]
  Downloading pyspark-3.2.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 38 kB/s
Collecting py4j==0.10.9.2
  Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 43.4 MB/s
Requirement already satisfied: pandas>=0.23.2 in /usr/local/lib/python3.7/dist-packages (from pyspark[sql]) (1.1.5)
Requirement already satisfied: pyarrow>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from pyspark[sql]) (3.0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.2->pyspark[sql]) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.2->pyspark[sql]) (2.8.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.2->pyspark[sql]) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23.2->pyspark[sql]) (1.15.0)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805912 sha256=8ea9f23f2574b4b29013625829b1a0dbf4ffa9817515866bc8d554fad9169aef
  Stored in directory: /root/.cache/pip/wheels/0b/de/d2/9be5d59d7331c6c2a7c1b6d1a4f463ce107332b1ecd4e80718
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.2 pyspark-3.2.0

In [20]:
# ! pip install plotly chart-studio

# Quickstart: Pandas API on Spark

This is a short introduction to pandas API on Spark, geared mainly for new users. This notebook shows you some key differences between pandas and pandas API on Spark. You can run this examples by yourself in 'Live Notebook: pandas API on Spark' at [the quickstart page](https://spark.apache.org/docs/latest/api/python/getting_started/index.html).

Customarily, we import pandas API on Spark as follows:

In [2]:
import pandas as pd
import numpy as np
import pyspark.pandas as ps
from pyspark.sql import SparkSession

WARNING:root:'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.

## Object Creation

Creating a pandas-on-Spark Series by passing a list of values, letting pandas API on Spark create a default integer index:

In [ ]:
s = ps.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a pandas-on-Spark DataFrame by passing a dict of objects that can be converted to series-like.

In [ ]:
psdf = ps.DataFrame(
    {'a': [1, 2, 3, 4, 5, 6],
     'b': [100, 200, 300, 400, 500, 600],
     'c': ["one", "two", "three", "four", "five", "six"]},
    index=[10, 20, 30, 40, 50, 60])

In [ ]:
psdf

    a    b      c
10  1  100    one
20  2  200    two
30  3  300  three
40  4  400   four
50  5  500   five
60  6  600    six

Creating a pandas DataFrame by passing a numpy array, with a datetime index and labeled columns:

In [ ]:
dates = pd.date_range('20130101', periods=6)

In [ ]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pdf = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [ ]:
pdf

                   A         B         C         D
2013-01-01 -0.591988 -0.061211 -0.671340 -1.815441
2013-01-02  0.291703 -0.378585 -0.561420 -0.903600
2013-01-03 -0.470306 -0.982832  0.622419  0.395675
2013-01-04  1.470425  0.404717 -0.206056 -0.107090
2013-01-05  0.408221 -0.089715  1.043771 -0.977181
2013-01-06 -0.253861  0.381943 -1.582774  0.657763

Now, this pandas DataFrame can be converted to a pandas-on-Spark DataFrame

In [ ]:
psdf = ps.from_pandas(pdf)

In [ ]:
type(psdf)

pyspark.pandas.frame.DataFrame

It looks and behaves the same as a pandas DataFrame.

In [ ]:
psdf

                   A         B         C         D
2013-01-01 -0.591988 -0.061211 -0.671340 -1.815441
2013-01-02  0.291703 -0.378585 -0.561420 -0.903600
2013-01-03 -0.470306 -0.982832  0.622419  0.395675
2013-01-04  1.470425  0.404717 -0.206056 -0.107090
2013-01-05  0.408221 -0.089715  1.043771 -0.977181
2013-01-06 -0.253861  0.381943 -1.582774  0.657763

Also, it is possible to create a pandas-on-Spark DataFrame from Spark DataFrame easily.

Creating a Spark DataFrame from pandas DataFrame

In [ ]:
spark = SparkSession.builder.getOrCreate()

In [ ]:
sdf = spark.createDataFrame(pdf)

In [ ]:
sdf.show()

+-------------------+--------------------+--------------------+--------------------+
|                  A|                   B|                   C|                   D|
+-------------------+--------------------+--------------------+--------------------+
|-0.5919880391183703|-0.06121147948114582| -0.6713397422342151| -1.8154406671250936|
| 0.2917026627651955| -0.3785847384595863| -0.5614199953189347| -0.9035999482926194|
|-0.4703060614492167| -0.9828317350787498|  0.6224185375426128|  0.3956751993140749|
| 1.4704246750151457|  0.4047173850332643|-0.20605565374982995|-0.10709023789897315|
|0.40822054223775084|-0.08971538488479623|        1.0437707087| -0.9771812730075743|
|-0.2538607761655294|  0.3819425924203704| -1.5827736852407304|  0.6577626912976506|
+-------------------+--------------------+--------------------+--------------------+

Creating pandas-on-Spark DataFrame from Spark DataFrame.

In [ ]:
psdf = sdf.to_pandas_on_spark()

In [ ]:
psdf

          A         B         C         D
0 -0.591988 -0.061211 -0.671340 -1.815441
1  0.291703 -0.378585 -0.561420 -0.903600
2 -0.470306 -0.982832  0.622419  0.395675
3  1.470425  0.404717 -0.206056 -0.107090
4  0.408221 -0.089715  1.043771 -0.977181
5 -0.253861  0.381943 -1.582774  0.657763

Having specific [dtypes](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-dtypes) . Types that are common to both Spark and pandas are currently supported.

In [ ]:
psdf.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

Here is how to show top rows from the frame below.

Note that the data in a Spark dataframe does not preserve the natural order by default. The natural order can be preserved by setting `compute.ordered_head` option but it causes a performance overhead with sorting internally.

In [ ]:
psdf.head()

          A         B         C         D
0 -0.591988 -0.061211 -0.671340 -1.815441
1  0.291703 -0.378585 -0.561420 -0.903600
2 -0.470306 -0.982832  0.622419  0.395675
3  1.470425  0.404717 -0.206056 -0.107090
4  0.408221 -0.089715  1.043771 -0.977181

Displaying the index, columns, and the underlying numpy data.

In [ ]:
psdf.index

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [ ]:
psdf.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
psdf.to_numpy()

array([[-0.59198804, -0.06121148, -0.67133974, -1.81544067],
       [ 0.29170266, -0.37858474, -0.56142   , -0.90359995],
       [-0.47030606, -0.98283174,  0.62241854,  0.3956752 ],
       [ 1.47042468,  0.40471739, -0.20605565, -0.10709024],
       [ 0.40822054, -0.08971538,  1.04377071, -0.97718127],
       [-0.25386078,  0.38194259, -1.58277369,  0.65776269]])

Showing a quick statistic summary of your data

In [ ]:
psdf.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.142366 -0.120947 -0.225900 -0.458312
std    0.765292  0.518264  0.947016  0.938891
min   -0.591988 -0.982832 -1.582774 -1.815441
25%   -0.470306 -0.378585 -0.671340 -0.977181
50%   -0.253861 -0.089715 -0.561420 -0.903600
75%    0.408221  0.381943  0.622419  0.395675
max    1.470425  0.404717  1.043771  0.657763

Transposing your data

In [ ]:
psdf.T

          0         1         2         3         4         5
A -0.591988  0.291703 -0.470306  1.470425  0.408221 -0.253861
B -0.061211 -0.378585 -0.982832  0.404717 -0.089715  0.381943
C -0.671340 -0.561420  0.622419 -0.206056  1.043771 -1.582774
D -1.815441 -0.903600  0.395675 -0.107090 -0.977181  0.657763

Sorting by its index

In [ ]:
psdf.sort_index(ascending=False)

          A         B         C         D
5 -0.253861  0.381943 -1.582774  0.657763
4  0.408221 -0.089715  1.043771 -0.977181
3  1.470425  0.404717 -0.206056 -0.107090
2 -0.470306 -0.982832  0.622419  0.395675
1  0.291703 -0.378585 -0.561420 -0.903600
0 -0.591988 -0.061211 -0.671340 -1.815441

Sorting by value

In [ ]:
psdf.sort_values(by='B')

          A         B         C         D
2 -0.470306 -0.982832  0.622419  0.395675
1  0.291703 -0.378585 -0.561420 -0.903600
4  0.408221 -0.089715  1.043771 -0.977181
0 -0.591988 -0.061211 -0.671340 -1.815441
5 -0.253861  0.381943 -1.582774  0.657763
3  1.470425  0.404717 -0.206056 -0.107090

## Missing Data
Pandas API on Spark primarily uses the value `np.nan` to represent missing data. It is by default not included in computations.

In [ ]:
pdf1 = pdf.reindex(index=dates[0:4], columns=list(pdf.columns) + ['E'])

In [ ]:
pdf1.loc[dates[0]:dates[1], 'E'] = 1

In [ ]:
psdf1 = ps.from_pandas(pdf1)

In [ ]:
psdf1

                   A         B         C         D    E
2013-01-01 -0.591988 -0.061211 -0.671340 -1.815441  1.0
2013-01-02  0.291703 -0.378585 -0.561420 -0.903600  1.0
2013-01-03 -0.470306 -0.982832  0.622419  0.395675  NaN
2013-01-04  1.470425  0.404717 -0.206056 -0.107090  NaN

To drop any rows that have missing data.

In [ ]:
psdf1.dropna(how='any')

                   A         B        C         D    E
2013-01-01 -0.591988 -0.061211 -0.67134 -1.815441  1.0
2013-01-02  0.291703 -0.378585 -0.56142 -0.903600  1.0

Filling missing data.

In [ ]:
psdf1.fillna(value=5)

                   A         B         C         D    E
2013-01-01 -0.591988 -0.061211 -0.671340 -1.815441  1.0
2013-01-02  0.291703 -0.378585 -0.561420 -0.903600  1.0
2013-01-03 -0.470306 -0.982832  0.622419  0.395675  5.0
2013-01-04  1.470425  0.404717 -0.206056 -0.107090  5.0

## Operations

### Stats
Performing a descriptive statistic:

In [ ]:
psdf.mean()

A    0.142366
B   -0.120947
C   -0.225900
D   -0.458312
dtype: float64

### Spark Configurations

Various configurations in PySpark could be applied internally in pandas API on Spark.
For example, you can enable Arrow optimization to hugely speed up internal pandas conversion. See also <a href="https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html">PySpark Usage Guide for Pandas with Apache Arrow</a> in PySpark documentation.

In [ ]:
prev = spark.conf.get("spark.sql.execution.arrow.enabled")  # Keep its default value.
ps.set_option("compute.default_index_type", "distributed")  # Use default index prevent overhead.
import warnings
warnings.filterwarnings("ignore")  # Ignore warnings coming from Arrow optimizations.

In [ ]:
spark.conf.set("spark.sql.execution.arrow.enabled", True)
%timeit ps.range(300000).to_pandas()

1 loop, best of 5: 428 ms per loop

In [ ]:
spark.conf.set("spark.sql.execution.arrow.enabled", False)
%timeit ps.range(300000).to_pandas()

1 loop, best of 5: 1.54 s per loop

In [ ]:
ps.reset_option("compute.default_index_type")
spark.conf.set("spark.sql.execution.arrow.enabled", prev)  # Set its default value back.

## Grouping
By “group by” we are referring to a process involving one or more of the following steps:

- Splitting the data into groups based on some criteria
- Applying a function to each group independently
- Combining the results into a data structure

In [13]:
psdf = ps.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B': ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                    'C': np.random.randn(8),
                    'D': np.random.randn(8)})

In [14]:
psdf

     A      B         C         D
0  foo    one  0.274401 -0.042168
1  bar    one -0.616229  0.321869
2  foo    two -0.864045  0.506349
3  bar  three  1.094239  0.370637
4  foo    two  1.633860  0.223912
5  bar    two  0.535155 -0.580801
6  foo    one -0.601735 -0.169111
7  foo  three  0.342660  0.102133

Grouping and then applying the [sum()](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.groupby.GroupBy.sum.html) function to the resulting groups.

In [15]:
psdf.groupby('A').sum()

            C         D
A
bar  1.013165  0.111706
foo  0.785141  0.621114

Grouping by multiple columns forms a hierarchical index, and again we can apply the sum function.

In [16]:
psdf.groupby(['A', 'B']).sum()

                  C         D
A   B
foo one   -0.327334 -0.211280
    two    0.769815  0.730261
bar three  1.094239  0.370637
    one   -0.616229  0.321869
foo three  0.342660  0.102133
bar two    0.535155 -0.580801

### Advanced Grouping

In [134]:
from pyspark.sql.types import (
    BooleanType,
    StringType,
    StructField,
    StructType,
)


spark = SparkSession.builder.getOrCreate()

event_1 = {
    "id": "001",
    "_dt": "2021",
    "_version": "1.0.0",
    "_type": "lyst_entity",
    "foo": '"foo1"',
    # "`live.core.attr`": '{"value": "1"}',
    "live.core.attr": '{"value": "1"}',
    "c_create_dt": "2021-01-01T00:00:00Z",
    "_compacted": True,
    "c_flattened": True,
}

event_2 = {
    "id": "001",
    "_dt": "2021",
    "_version": "1.0.0",
    "_type": "lyst_entity",
    "foo": '"foo2"',
    # "`live.core.attr`": '{"value": "2"}',
    "live.core.attr": '{"value": "2"}',
    "_compacted": False,
    "c_flattened": True,
}

schema = StructType([StructField("_compacted",BooleanType(),True),
                StructField("_dt",StringType(),True),
                StructField("_type",StringType(),True),
                StructField("_version",StringType(),True),
                StructField("c_create_dt",StringType(),True),
                StructField("c_flattened",BooleanType(),True),
                StructField("foo",StringType(),True),
                StructField("id",StringType(),True),
                # StructField("live.core.attr",StringType(),True)
                StructField("live.core.attr",StringType(),True)
                ]
            )

# psdf = spark.createDataFrame([event_1, event_2], schema=psdf.schema)
psdf = spark.createDataFrame([event_1, event_2], schema=schema)

def pandas_transform(group: pd.DataFrame) -> pd.DataFrame:
    return group

In [122]:
psdf.groupBy("id").count().show()

+---+-----+
| id|count|
+---+-----+
|001|    2|
+---+-----+

In [136]:
# psdf.groupBy("id").applyInPandas(pandas_transform, schema=psdf.schema)
psdf.groupBy("id").applyInPandas(pandas_transform, schema=schema)

AnalysisException: ignored

In [151]:
import pandas as pd  
from pyspark.sql.functions import pandas_udf, ceil
df = spark.createDataFrame(
    [(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0)],
    ("`id`", "`v.val`"))  
def normalize(pdf):
    v = pdf["`v.val`"]
    return pdf.assign(v=(v - v.mean()) / v.std())
df.groupby("`id`").applyInPandas(
    normalize, schema="`id` long, `v.val` double").show()

AnalysisException: ignored

In [152]:
df.printSchema()

root
 |-- `id`: long (nullable = true)
 |-- `v.val`: double (nullable = true)

In [153]:
df.schema.fieldNames()

['`id`', '`v.val`']

In [155]:
df.select("`dt`")

AnalysisException: ignored

In [123]:
psdf.printSchema()

root
 |-- _compacted: boolean (nullable = true)
 |-- _dt: string (nullable = true)
 |-- _type: string (nullable = true)
 |-- _version: string (nullable = true)
 |-- c_create_dt: string (nullable = true)
 |-- c_flattened: boolean (nullable = true)
 |-- foo: string (nullable = true)
 |-- id: string (nullable = true)
 |-- live.core.attr: string (nullable = true)

In [124]:
psdf.schema.fieldNames()

['_compacted',
 '_dt',
 '_type',
 '_version',
 'c_create_dt',
 'c_flattened',
 'foo',
 'id',
 'live.core.attr']

In [126]:
psdf.collect()

[Row(_compacted=True, _dt='2021', _type='lyst_entity', _version='1.0.0', c_create_dt='2021-01-01T00:00:00Z', c_flattened=True, foo='"foo1"', id='001', live.core.attr='{"value": "1"}'),
 Row(_compacted=False, _dt='2021', _type='lyst_entity', _version='1.0.0', c_create_dt=None, c_flattened=True, foo='"foo2"', id='001', live.core.attr='{"value": "2"}')]

In [127]:
psdf.show()

+----------+----+-----------+--------+--------------------+-----------+------+---+--------------+
|_compacted| _dt|      _type|_version|         c_create_dt|c_flattened|   foo| id|live.core.attr|
+----------+----+-----------+--------+--------------------+-----------+------+---+--------------+
|      true|2021|lyst_entity|   1.0.0|2021-01-01T00:00:00Z|       true|"foo1"|001|{"value": "1"}|
|     false|2021|lyst_entity|   1.0.0|                null|       true|"foo2"|001|{"value": "2"}|
+----------+----+-----------+--------+--------------------+-----------+------+---+--------------+

In [128]:
psdf.printSchema()

root
 |-- _compacted: boolean (nullable = true)
 |-- _dt: string (nullable = true)
 |-- _type: string (nullable = true)
 |-- _version: string (nullable = true)
 |-- c_create_dt: string (nullable = true)
 |-- c_flattened: boolean (nullable = true)
 |-- foo: string (nullable = true)
 |-- id: string (nullable = true)
 |-- live.core.attr: string (nullable = true)

In [129]:
psdf.select("`_dt`").show()

+----+
| _dt|
+----+
|2021|
|2021|
+----+

In [130]:
psdf.select("live.core.attr").show()

AnalysisException: ignored

In [131]:
psdf.select("`live.core.attr`").show()

+--------------+
|live.core.attr|
+--------------+
|{"value": "1"}|
|{"value": "2"}|
+--------------+

In [46]:
psdf.groupBy("id").applyInPandas(pandas_transform, schema=psdf.schema)

AnalysisException: ignored

## Plotting

In [7]:
pser = pd.Series(np.random.randn(1000),
                 index=pd.date_range('1/1/2000', periods=1000))

In [8]:
psser = ps.Series(pser)

In [9]:
psser = psser.cummax()

In [12]:
psser.plot()

AttributeError: ignored

On a DataFrame, the [plot()](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.DataFrame.plot.html) method is a convenience to plot all of the columns with labels:

In [ ]:
pdf = pd.DataFrame(np.random.randn(1000, 4), index=pser.index,
                   columns=['A', 'B', 'C', 'D'])

In [ ]:
psdf = ps.from_pandas(pdf)

In [ ]:
psdf = psdf.cummax()

In [ ]:
type(psdf)

pyspark.pandas.frame.DataFrame

In [ ]:
psdf.plot()

AttributeError: ignored

For more details, [Plotting](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/frame.html#plotting) documentation.

## Getting data in/out

### CSV

CSV is straightforward and easy to use. See [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.DataFrame.to_csv.html) to write a CSV file and [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.read_csv.html) to read a CSV file.

In [ ]:
psdf.to_csv('foo.csv')
ps.read_csv('foo.csv').head(10)

### Parquet

Parquet is an efficient and compact file format to read and write faster. See [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.DataFrame.to_paruqet.html) to write a Parquet file and [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.read_parquet.html) to read a Parquet file.

In [ ]:
psdf.to_parquet('bar.parquet')
ps.read_parquet('bar.parquet').head(10)

### Spark IO

In addition, pandas API on Spark fully supports Spark's various datasources such as ORC and an external datasource.  See [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.DataFrame.to_orc.html) to write it to the specified datasource and [here](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.read_orc.html) to read it from the datasource.

In [ ]:
psdf.to_spark_io('zoo.orc', format="orc")
ps.read_spark_io('zoo.orc', format="orc").head(10)

See the [Input/Output](https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/io.html) documentation for more details.